import "./globals.css";
import { Providers } from "@/components/providers";
import { Poppins } from "@next/font/google";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Aurwan",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
